name: Deploy Static Website to AWS S3

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Terraform and S3 Deployment
    runs-on: ubuntu-latest

    steps:

      # Step 1 - Checkout repository code
      - name: Checkout Code
        uses: actions/checkout@v4

      # Step 2 - Configure AWS Credentials
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      # Step 3 - Install Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      # Step 4 - Terraform Init
      - name: Terraform Init
        working-directory: terraform
        run: terraform init

      # Step 5 - Terraform Validate
      - name: Terraform Validate
        working-directory: terraform
        run: terraform validate

      # Step 6 - Terraform Plan
      - name: Terraform Plan
        working-directory: terraform
        run: terraform plan

      # Step 7 - Terraform Apply
      - name: Terraform Apply
        working-directory: terraform
        run: terraform apply -auto-approve

      # Step 8 - Upload Website Files to S3
      - name: Upload Website Files
        run: aws s3 sync website/ s3://veda-devops-static-site-2026
